# Generated by Django 2.2.5 on 2019-11-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bali_Offer',
            fields=[
                ('bali_offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bali_offer_date', models.DateField()),
                ('bali_offer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carol_Image',
            fields=[
                ('carol_image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('carom_image_date', models.DateField()),
                ('carol_image_category', models.CharField(choices=[('T', 'Teakwood'), ('G', 'Gift'), ('A', 'Antique')], max_length=1)),
                ('carol_image_desc', models.TextField()),
                ('carol_image_loc', models.ImageField(upload_to='bali/image/offers/%Y/%m/%d')),
                ('carol_image_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
