# Generated by Django 2.2.5 on 2019-11-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali', '0003_auto_20191109_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_loc',
            field=models.ImageField(upload_to='image/%Y/%m/%d'),
        ),
    ]
