# Generated by Django 2.2.5 on 2019-11-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali', '0004_auto_20191109_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_category',
            field=models.CharField(choices=[('A', 'Antique'), ('T', 'Teakwood'), ('G', 'Gift')], max_length=1),
        ),
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_loc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
