# Generated by Django 2.2.5 on 2019-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali', '0005_auto_20191109_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_category',
            field=models.CharField(choices=[('A', 'Antique'), ('G', 'Gift'), ('T', 'Teakwood')], max_length=1),
        ),
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_loc',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m'),
        ),
    ]
