# Generated by Django 2.2.5 on 2019-11-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali', '0006_auto_20191109_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bali_offer',
            name='bali_offer_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_category',
            field=models.CharField(choices=[('G', 'Gift'), ('A', 'Antique'), ('T', 'Teakwood')], max_length=1),
        ),
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_desc',
            field=models.CharField(max_length=30),
        ),
    ]
