# Generated by Django 2.2.5 on 2019-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali', '0007_auto_20191109_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carol_image',
            old_name='carol_image_loc',
            new_name='carol_image_loc1',
        ),
        migrations.RemoveField(
            model_name='bali_offer',
            name='bali_offer_id',
        ),
        migrations.RemoveField(
            model_name='carol_image',
            name='carol_image_id',
        ),
        migrations.AddField(
            model_name='bali_offer',
            name='bali_offer_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bali_offer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carol_image',
            name='carol_image_loc2',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m'),
        ),
        migrations.AddField(
            model_name='carol_image',
            name='carol_image_loc3',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m'),
        ),
        migrations.AddField(
            model_name='carol_image',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_category',
            field=models.CharField(choices=[('Antique', 'Antique'), ('Gift', 'Gift'), ('TeakWood', 'TeakWood')], max_length=20),
        ),
    ]
