# Generated by Django 2.2.5 on 2019-11-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali', '0009_auto_20191109_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_category',
            field=models.CharField(choices=[('TeakWood', 'TeakWood'), ('Antique', 'Antique'), ('Gift', 'Gift')], max_length=20),
        ),
    ]
