# Generated by Django 2.2.5 on 2019-11-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali', '0010_auto_20191109_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_category',
            field=models.CharField(choices=[('Gift', 'Gift'), ('Antique', 'Antique'), ('TeakWood', 'TeakWood')], max_length=20),
        ),
    ]
