# Generated by Django 2.2.5 on 2019-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali', '0011_auto_20191109_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carol_image',
            old_name='carol_image_desc',
            new_name='carol_image_desc1',
        ),
        migrations.RemoveField(
            model_name='carol_image',
            name='carol_image_category',
        ),
        migrations.AddField(
            model_name='carol_image',
            name='carol_image_category1',
            field=models.CharField(choices=[('Gift', 'Gift'), ('TeakWood', 'TeakWood'), ('Antique', 'Antique')], default='TeakWood', max_length=20),
        ),
        migrations.AddField(
            model_name='carol_image',
            name='carol_image_category2',
            field=models.CharField(choices=[('Gift', 'Gift'), ('TeakWood', 'TeakWood'), ('Antique', 'Antique')], default='Antique', max_length=20),
        ),
        migrations.AddField(
            model_name='carol_image',
            name='carol_image_category3',
            field=models.CharField(choices=[('Gift', 'Gift'), ('TeakWood', 'TeakWood'), ('Antique', 'Antique')], default='Gift', max_length=20),
        ),
        migrations.AddField(
            model_name='carol_image',
            name='carol_image_desc2',
            field=models.CharField(default='Antique', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carol_image',
            name='carol_image_desc3',
            field=models.CharField(default='Gift', max_length=30),
            preserve_default=False,
        ),
    ]
