# Generated by Django 2.2.5 on 2019-11-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bali', '0012_auto_20191109_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_category1',
            field=models.CharField(choices=[('Gift', 'Gift'), ('Antique', 'Antique'), ('TeakWood', 'TeakWood')], default='TeakWood', max_length=20),
        ),
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_category2',
            field=models.CharField(choices=[('Gift', 'Gift'), ('Antique', 'Antique'), ('TeakWood', 'TeakWood')], default='Antique', max_length=20),
        ),
        migrations.AlterField(
            model_name='carol_image',
            name='carol_image_category3',
            field=models.CharField(choices=[('Gift', 'Gift'), ('Antique', 'Antique'), ('TeakWood', 'TeakWood')], default='Gift', max_length=20),
        ),
    ]
